apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: build-tool
  creationTimestamp: '2021-05-07T20:21:56Z'
  generation: 18
  labels:
    app.kubernetes.io/version: '0.1'
  name: maven
  resourceVersion: '517820653'
  selfLink: /apis/tekton.dev/v1beta1/clustertasks/maven
  uid: bc547418-0a17-4536-bd3f-2d052a16ea8e
spec:
  description: This Task can be used to run a Maven build.
  params:
    - default: >-
        gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
      description: Maven base image
      name: MAVEN_IMAGE
      type: string
    - default:
        - package
      description: maven goals to run
      name: GOALS
      type: array
    - default: ''
      description: The Maven repository mirror url
      name: MAVEN_MIRROR_URL
      type: string
    - default: ''
      description: The username for the proxy server
      name: PROXY_USER
      type: string
    - default: ''
      description: The password for the proxy server
      name: PROXY_PASSWORD
      type: string
    - default: ''
      description: Port number for the proxy server
      name: PROXY_PORT
      type: string
    - default: ''
      description: Proxy server Host
      name: PROXY_HOST
      type: string
    - default: ''
      description: Non proxy server host
      name: PROXY_NON_PROXY_HOSTS
      type: string
    - default: http
      description: Protocol for the proxy ie http or https
      name: PROXY_PROTOCOL
      type: string
  steps:
    - env:
        - name: settings
          valueFrom:
            configMapKeyRef:
              key: settings.xml
              name: settings-maven
      image: 'registry.access.redhat.com/ubi8/ubi-minimal:8.2'
      name: mvn-settings
      resources: {}
      script: |
        #!/usr/bin/env bash 
        echo $settings > $(workspaces.maven-settings.path)/settings.xml  
    - args:
        - '-s'
        - $(workspaces.maven-settings.path)/settings.xml
        - $(params.GOALS)
        - '-Dmaven.test.skip=true'
      command:
        - /usr/bin/mvn
      image: $(params.MAVEN_IMAGE)
      name: mvn-goals
      resources: {}
      workingDir: $(workspaces.source.path)
  workspaces:
    - description: The workspace consisting of maven project.
      name: source
    - description: >-
        The workspace consisting of the custom maven settings provided by the
        user.
      name: maven-settings
